### ISSUE TITLE
Org Checklist

### ISSUE THREAD

**Issue by PatheticMustan** [Prodigy-Hacking/ProdigyMathGameHacking#148]
- [x] Move redirector to its own repo
- [x] Move cheat menu to its own repo
- [x] Convert all old hacks into new hacks, and remove the old hacks folder
- [x] Add better suggestion area

**Comment by Exoticc** [comment]
@PatheticMustan i cannot find/make hacks anymore but i am more then willing to help with anything else! So if you need me to do anything from the checklist above i can.

P.S. If you haven't already realized i'm Magmischief (i changed my github username to Exoticc)

**Comment by Exoticc** [comment]
@PatheticMustan if you need help with any of the above just let me know.

**Comment by Avn1114** [comment]
https://github.com/Prodigy-Hacking/RedirectorHack
Here, can y'all do the rest?

**Comment by TNThacker2015** [comment]
ok this done
