### ISSUE TITLE
Update WCM

### ISSUE THREAD

**Issue by PatheticMustan** [Prodigy-Hacking/ProdigyMathGameHacking#318]
So WCM hasn't been updated in a long time. We really should update it, but Will is the only real maintainer of it.

Related to #285 

Things to update:

- [x] Update UI, it kinda looks dumb (#338)
- [x] Picker to get only certain items, and a certain amount.
- [x] Squish Inventory Hacks into a squishier area
- [ ] Auto-run assignRandomSpells when a broken pet is detected
- [x] Update Battle hacks
- [x] Remove "test"
- [x] Update broken hacks in Miscellaneous (snowball crasher, finish tutorial) (#316)
- [x] Add more miscellaneous hacks
- [x] Custom morph hacks
- [x] Add more validation to battle hacks (#252)
- [x] OwO text(#359)
- [x] Remove archives from teleport (#255)
- [x] Player state saving (issue: #283, PR: #349)
- [x] Arena Points Button

**Comment by PatheticMustan** [comment]
Need help with this one, @KryptoCrash @TNThacker2015 @ArcerionDev. Only collaborators will be able to comment on this issue.

**Comment by PatheticMustan** [comment]
e431c616d08c24ebfc9b6700dcabbdf3fed61aed

**Comment by ArcerionDev** [comment]
by OwO text do you mean keep it or get rid of it @PatheticMustan

**Comment by PatheticMustan** [comment]
ab20d14342079bbb50dca151cb33eb81144e151a

**Comment by SwxtchCode** [comment]
#349

**Comment by BoredFishRE** [comment]
@PatheticMustan OwO text get rid of or add?

**Comment by PatheticMustan** [comment]
add as button

**Comment by BoredFishRE** [comment]
OwO button completed #359

**Comment by ArcerionDev** [comment]
@PatheticMustan can you explain each improvement so we can work on them, for example, "rainbow" and "Squish Inventory Hacks into a squishier area" aren't very clear

**Comment by BoredFishRE** [comment]
are we gonna do this lol

**Comment by PatheticMustan** [comment]
wughhhhhhhhhhhhhhhhhhh procrastination

**Comment by PatheticMustan** [comment]
ok non feature related changes planned:

not sure what this is
https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/blob/770b21e07b2d81082f96698fecad3e1d66526a9c/willsCheatMenu/src/index.ts#L28

maybe merge Hack and Toggler
https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/blob/770b21e07b2d81082f96698fecad3e1d66526a9c/willsCheatMenu/src/index.ts#L69-L138

remove
https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/blob/770b21e07b2d81082f96698fecad3e1d66526a9c/willsCheatMenu/src/index.ts#L60-L67

**Comment by PatheticMustan** [comment]
I'd also like to update the location images...

**Comment by ArcerionDev** [comment]
I forgot about that

**Comment by ArcerionDev** [comment]
Fixed number 14.

**Comment by BoredFishRE** [comment]
https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/commit/66072cfbc9b044ed42e86ba74bcbfcc775b7865b done this. sorta. just made it so whenever get all pets or get all epics is run, the fix battle crash script is run.

**Comment by PatheticMustan** [comment]
no

the problem is when they switch to new pets, fix battle crash only fixes the current pet team

**Comment by BoredFishRE** [comment]
hm. what causes the problem for the crashes.

**Comment by PatheticMustan** [comment]
invalid spells

**Comment by PatheticMustan** [comment]
I'm working on it right now

**Comment by BoredFishRE** [comment]
alright, was gonna say, if we can detect when someone switches pets, it'll run it.

**Comment by BoredFishRE** [comment]
or we could just have it run it every 5 seconds lol

**Comment by BoredFishRE** [comment]
that's the easiest

**Comment by ArcerionDev** [comment]
It resets spells though, so it would get rid of the effects on the edit pet hack, so no

**Comment by ArcerionDev** [comment]
Alright, we just need to work out the above issue, and then we're good

**Comment by PatheticMustan** [comment]
> or we could just have it run it every 5 seconds lol

please don't
it just randomizes the spells

**Comment by BoredFishRE** [comment]
ight so only problem is detecting when it happens.

**Comment by BoredFishRE** [comment]
or we could just make it so every time they switch pets, it reminds them to run the fix battle crash, if it hasn't been run

**Comment by PatheticMustan** [comment]
no
we just have to rev assignRandomSpells
I swear I'll work on it, I'm just busy fixing up some dependency stuffs

**Comment by BoredFishRE** [comment]
so basically that's the last thing to do. should we start on the stuff in #roadmap?

**Comment by BoredFishRE** [comment]
we promised we would do that ngl

**Comment by ArcerionDev** [comment]
alright, we need to figure out exactly _what_ causes this to happen. We know it's because of the corrupted spells, but how do we detect it

**Comment by PatheticMustan** [comment]
If you look in the gamemin, assignRandomSpells seems to get two arrays, (a min and max possibly?) and somehow picks a random from there

all we need to do is repurpose it

**Comment by PatheticMustan** [comment]
Bump, we're so close

**Comment by LeoBadeaux** [comment]
Let's merge all discussion for that 1 auto-fix battle crash to #588
