### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by PatheticMustan** [Prodigy-Hacking/ProdigyMathGameHacking#800]
This is embarrassing... We completely forgot about #412!
It would be cool to work on this until 5k. Any additional suggestions will be saved for road to 6k.

- [ ] Fix broken hacks on harmony island
- [ ] Hosted arena hacks
- [x] Online Dashboard
- [x] Eval console
- [x] An index page for the extension
- [x] Easy mode
- [x] Quest hacks
- [x] Toggle click teleporting
- [ ] Triggering battles with certain enemies
- [x] Detailed pet editing
- [x] Morph hacks
- [x] Custom P-NP url
- [ ] Analytics
  - [ ] Track number of uses per each grade, this will give us insight to user age
  - [ ] Track the amount of times each hack is used.
  - [ ] Track to see if any students are in Leo's school county district
  - [ ] Track usage over time, would be cool to see the graph of uses per day go up when the school year starts and during breaks and the likes
  - [ ] Track amount of players by province/state/region
  - [ ] Track total hours played on prodigy using our hacks

**Comment by PatheticMustan** [comment]
Also cool, we got #800! What a cool number!

**Comment by LeoBadeaux** [comment]
Elaborate on "An index page for the extension"

**Comment by ChickenOnYT** [comment]
Elaborate on "An index page for the extension"

**Comment by ChickenOnYT** [comment]
i accidentally checked stuff sorry

**Comment by PatheticMustan** [comment]
![image](https://user-images.githubusercontent.com/35382971/113371564-aaea5b00-9334-11eb-9f8d-9f03651892d9.png)
when clicky on extension pop up go wheeee

**Comment by ChickenOnYT** [comment]
oo cool

**Comment by LeoBadeaux** [comment]
Ah yes but what do we put on it?

**Comment by ChickenOnYT** [comment]
links to digitalteal.com

**Comment by PatheticMustan** [comment]
yikes..... we're at 5k... uh

**Comment by ArcerionDev** [comment]
From now on, let's not set a deadline for ourselves, it never works out anyway.

**Comment by PatheticMustan** [comment]
Tmw we hit 7k before we fix any of the issues we make for ourselves

**Comment by LeoBadeaux** [comment]
> Toggle click teleporting
This is pretty easy, just set walkspeed to like 500, we could have somebody add a button to enable/disable that.

**Comment by hostedposted** [comment]
what should the Online Dashboard do?

**Comment by hostedposted** [comment]
> > Toggle click teleporting
> 
> This is pretty easy, just set walkspeed to like 500, we could have somebody add a button to enable/disable that.

@LeoBadeaux problem is walkspeed was in ``_.player.user`` but that's deleted now

**Comment by hostedposted** [comment]
Walkspeed is now in ``_.player._playerContainer.walkSpeed``. So we could use this code ``_.player._playerContainer.walkSpeed = 500``

**Comment by hostedposted** [comment]
added it

**Comment by Phenomenon1337** [comment]
_.constants.constants["GameConstants.Battle.SKIP_ENEMY_TURN"] = true; | leaving so i can make smth after school, i have no where to put this sorry

**Comment by 4evera1one** [comment]
soo uh, what should the online dashboard do? i can try to make it

**Comment by 4evera1one** [comment]
i should be able to make easymode in a few hours when i get out of this summer school .-.

**Comment by hostedposted** [comment]
agr and I made a dashboard: https://prodigy-dashboard.hostedposted.com/

**Comment by hostedposted** [comment]
I could add analytics.

**Comment by PatheticMustan** [comment]
holy shit we're bad
